# Generated by Django 4.2.4 on 2025-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(default='dev.to', max_length=50)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
